### PR TITLE
Install changelog-bot

### PR DESCRIPTION
**Pull request by SeanTAllen**

### CODE REVIEW

**Comment by mfelsche** [comment]
is the secret name correct? should it be RELEASE_TOKEN ? or are you gonna add the missing GITHUB_TOKEN?

**Comment by SeanTAllen** [comment]
@mfelsche Here comes the GH actions lesson...

so GITHUB_TOKEN is supplied by GH. If you push using that token. No other actions will be trigger. 
This is what we want with the changelog-bot.

For releases, when we push, we need those pushes to trigger additional actions, so we create a personal access token owned by Main and use that. By convention, we call it RELEASE_TOKEN.

I should add this to the contributors repo, shouldn't I?

**Comment by mfelsche** [comment]
Yeah, adding this to the contributors repo makes sense, to avoid future confusion.

**Comment by SeanTAllen** [comment]
@mfelsche so it doesn't get forgotten, i added it as an issue on the contributors repo.

**Pull request merged**
